# Generated by Django 4.1.7 on 2024-03-08 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
